// Defines colors used in Canvas (using W3 names)

//  PrimeNG stuffies
import { Injectable }                 from '@angular/core';

// PrimeNG stuffies
import { SelectItem }                 from 'primeng/primeng';  

@Injectable()
export class CanvasColors {

    colors: SelectItem[];
    
    constructor() {

        this.colors = [
            {label:'transparent',            value:{id:1, name: 'transparent',           code: 'transparent'}},
            {label:'AliceBlue',              value:{id:1, name: 'AliceBlue',             code: '#F0F8FF'}},
            {label:'AntiqueWhite',           value:{id:1, name: 'AntiqueWhite',          code: '#FAEBD7'}},
            {label:'Aqua',                   value:{id:1, name: 'Aqua',                  code: '#00FFFF'}},
            {label:'Aquamarine',             value:{id:1, name: 'Aquamarine',            code: '#7FFFD4'}},
            {label:'Azure',                  value:{id:1, name: 'Azure',                 code: '#F0FFFF'}},
            {label:'Beige',                  value:{id:1, name: 'Beige',                 code: '#F5F5DC'}},
            {label:'Bisque',                 value:{id:1, name: 'Bisque',                code: '#FFE4C4'}},
            {label:'Black',                  value:{id:1, name: 'Black',                 code: '#000000'}},
            {label:'BlanchedAlmond',         value:{id:1, name: 'BlanchedAlmond',        code: '#FFEBCD'}},
            {label:'Blue',                   value:{id:1, name: 'Blue',                  code: '#0000FF'}},
            {label:'BlueViolet',             value:{id:1, name: 'BlueViolet',            code: '#8A2BE2'}},
            {label:'Brown',                  value:{id:1, name: 'Brown',                 code: '#A52A2A'}},
            {label:'BurlyWood',              value:{id:1, name: 'BurlyWood',             code: '#DEB887'}},
            {label:'CadetBlue',              value:{id:1, name: 'CadetBlue',             code: '#5F9EA0'}},
            {label:'Chartreuse',             value:{id:1, name: 'Chartreuse',            code: '#7FFF00'}},
            {label:'Chocolate',              value:{id:1, name: 'Chocolate',             code: '#D2691E'}},
            {label:'Coral',                  value:{id:1, name: 'Coral',                 code: '#FF7F50'}},
            {label:'CornflowerBlue',         value:{id:1, name: 'CornflowerBlue',        code: '#6495ED'}},
            {label:'Cornsilk',               value:{id:1, name: 'Cornsilk',              code: '#FFF8DC'}},
            {label:'Crimson',                value:{id:1, name: 'Crimson',               code: '#DC143C'}},
            {label:'Cyan',                   value:{id:1, name: 'Cyan',                  code: '#00FFFF'}},
            {label:'DarkBlue',               value:{id:1, name: 'DarkBlue',              code: '#00008B'}},
            {label:'DarkCyan',               value:{id:1, name: 'DarkCyan',              code: '#008B8B'}},
            {label:'DarkGoldenRod',          value:{id:1, name: 'DarkGoldenRod',         code: '#B8860B'}},
            {label:'DarkGray',               value:{id:1, name: 'DarkGray',              code: '#A9A9A9'}},
            {label:'DarkGrey',               value:{id:1, name: 'DarkGrey',              code: '#A9A9A9'}},
            {label:'DarkGreen',              value:{id:1, name: 'DarkGreen',             code: '#006400'}},
            {label:'DarkKhaki',              value:{id:1, name: 'DarkKhaki',             code: '#BDB76B'}},
            {label:'DarkMagenta',            value:{id:1, name: 'DarkMagenta',           code: '#8B008B'}},
            {label:'DarkOliveGreen',         value:{id:1, name: 'DarkOliveGreen',        code: '#556B2F'}},
            {label:'DarkOrange',             value:{id:1, name: 'DarkOrange',            code: '#FF8C00'}},
            {label:'DarkOrchid',             value:{id:1, name: 'DarkOrchid',            code: '#9932CC'}},
            {label:'DarkRed',                value:{id:1, name: 'DarkRed',               code: '#8B0000'}},
            {label:'DarkSalmon',             value:{id:1, name: 'DarkSalmon',            code: '#E9967A'}},
            {label:'DarkSeaGreen',           value:{id:1, name: 'DarkSeaGreen',          code: '#8FBC8F'}},
            {label:'DarkSlateBlue',          value:{id:1, name: 'DarkSlateBlue',         code: '#483D8B'}},
            {label:'DarkSlateGray',          value:{id:1, name: 'DarkSlateGray',         code: '#2F4F4F'}},
            {label:'DarkSlateGrey',          value:{id:1, name: 'DarkSlateGrey',         code: '#2F4F4F'}},
            {label:'DarkTurquoise',          value:{id:1, name: 'DarkTurquoise',         code: '#00CED1'}},
            {label:'DarkViolet',             value:{id:1, name: 'DarkViolet',            code: '#9400D3'}},
            {label:'DeepPink',               value:{id:1, name: 'DeepPink',              code: '#FF1493'}},
            {label:'DeepSkyBlue',            value:{id:1, name: 'DeepSkyBlue',           code: '#00BFFF'}},
            {label:'DimGray',                value:{id:1, name: 'DimGray',               code: '#696969'}},
            {label:'DimGrey',                value:{id:1, name: 'DimGrey',               code: '#696969'}},
            {label:'DodgerBlue',             value:{id:1, name: 'DodgerBlue',            code: '#1E90FF'}},
            {label:'FireBrick',              value:{id:1, name: 'FireBrick',             code: '#B22222'}},
            {label:'FloralWhite',            value:{id:1, name: 'FloralWhite',           code: '#FFFAF0'}},
            {label:'ForestGreen',            value:{id:1, name: 'ForestGreen',           code: '#228B22'}},
            {label:'Fuchsia',                value:{id:1, name: 'Fuchsia',               code: '#FF00FF'}},
            {label:'Gainsboro',              value:{id:1, name: 'Gainsboro',             code: '#DCDCDC'}},
            {label:'GhostWhite',             value:{id:1, name: 'GhostWhite',            code: '#F8F8FF'}},
            {label:'Gold',                   value:{id:1, name: 'Gold',                  code: '#FFD700'}},
            {label:'GoldenRod',              value:{id:1, name: 'GoldenRod',             code: '#DAA520'}},
            {label:'Gray',                   value:{id:1, name: 'Gray',                  code: '#808080'}},
            {label:'Grey',                   value:{id:1, name: 'Grey',                  code: '#808080'}},
            {label:'Green',                  value:{id:1, name: 'Green',                 code: '#008000'}},
            {label:'GreenYellow',            value:{id:1, name: 'GreenYellow',           code: '#ADFF2F'}},
            {label:'HoneyDew',               value:{id:1, name: 'HoneyDew',              code: '#F0FFF0'}},
            {label:'HotPink',                value:{id:1, name: 'HotPink',               code: '#FF69B4'}},
            {label:'IndianRed ',             value:{id:1, name: 'IndianRed ',            code: '#CD5C5C'}},
            {label:'Indigo ',                value:{id:1, name: 'Indigo ',               code: '#4B0082'}},
            {label:'Ivory',                  value:{id:1, name: 'Ivory',                 code: '#FFFFF0'}},
            {label:'Khaki',                  value:{id:1, name: 'Khaki',                 code: '#F0E68C'}},
            {label:'Lavender',               value:{id:1, name: 'Lavender',              code: '#E6E6FA'}},
            {label:'LavenderBlush',          value:{id:1, name: 'LavenderBlush',         code: '#FFF0F5'}},
            {label:'LawnGreen',              value:{id:1, name: 'LawnGreen',             code: '#7CFC00'}},
            {label:'LemonChiffon',           value:{id:1, name: 'LemonChiffon',          code: '#FFFACD'}},
            {label:'LightBlue',              value:{id:1, name: 'LightBlue',             code: '#ADD8E6'}},
            {label:'LightCoral',             value:{id:1, name: 'LightCoral',            code: '#F08080'}},
            {label:'LightCyan',              value:{id:1, name: 'LightCyan',             code: '#E0FFFF'}},
            {label:'LightGoldenRodYellow',   value:{id:1, name: 'LightGoldenRodYellow',  code: '#FAFAD2'}},
            {label:'LightGray',              value:{id:1, name: 'LightGray',             code: '#D3D3D3'}},
            {label:'LightGrey',              value:{id:1, name: 'LightGrey',             code: '#D3D3D3'}},
            {label:'LightGreen',             value:{id:1, name: 'LightGreen',            code: '#90EE90'}},
            {label:'LightPink',              value:{id:1, name: 'LightPink',             code: '#FFB6C1'}},
            {label:'LightSalmon',            value:{id:1, name: 'LightSalmon',           code: '#FFA07A'}},
            {label:'LightSeaGreen',          value:{id:1, name: 'LightSeaGreen',         code: '#20B2AA'}},
            {label:'LightSkyBlue',           value:{id:1, name: 'LightSkyBlue',          code: '#87CEFA'}},
            {label:'LightSlateGray',         value:{id:1, name: 'LightSlateGray',        code: '#778899'}},
            {label:'LightSlateGrey',         value:{id:1, name: 'LightSlateGrey',        code: '#778899'}},
            {label:'LightSteelBlue',         value:{id:1, name: 'LightSteelBlue',        code: '#B0C4DE'}},
            {label:'LightYellow',            value:{id:1, name: 'LightYellow',           code: '#FFFFE0'}},
            {label:'Lime',                   value:{id:1, name: 'Lime',                  code: '#00FF00'}},
            {label:'LimeGreen',              value:{id:1, name: 'LimeGreen',             code: '#32CD32'}},
            {label:'Linen',                  value:{id:1, name: 'Linen',                 code: '#FAF0E6'}},
            {label:'Magenta',                value:{id:1, name: 'Magenta',               code: '#FF00FF'}},
            {label:'Maroon',                 value:{id:1, name: 'Maroon',                code: '#800000'}},
            {label:'MediumAquaMarine',       value:{id:1, name: 'MediumAquaMarine',      code: '#66CDAA'}},
            {label:'MediumBlue',             value:{id:1, name: 'MediumBlue',            code: '#0000CD'}},
            {label:'MediumOrchid',           value:{id:1, name: 'MediumOrchid',          code: '#BA55D3'}},
            {label:'MediumPurple',           value:{id:1, name: 'MediumPurple',          code: '#9370DB'}},
            {label:'MediumSeaGreen',         value:{id:1, name: 'MediumSeaGreen',        code: '#3CB371'}},
            {label:'MediumSlateBlue',        value:{id:1, name: 'MediumSlateBlue',       code: '#7B68EE'}},
            {label:'MediumSpringGreen',      value:{id:1, name: 'MediumSpringGreen',     code: '#00FA9A'}},
            {label:'MediumTurquoise',        value:{id:1, name: 'MediumTurquoise',       code: '#48D1CC'}},
            {label:'MediumVioletRed',        value:{id:1, name: 'MediumVioletRed',       code: '#C71585'}},
            {label:'MidnightBlue',           value:{id:1, name: 'MidnightBlue',          code: '#191970'}},
            {label:'MintCream',              value:{id:1, name: 'MintCream',             code: '#F5FFFA'}},
            {label:'MistyRose',              value:{id:1, name: 'MistyRose',             code: '#FFE4E1'}},
            {label:'Moccasin',               value:{id:1, name: 'Moccasin',              code: '#FFE4B5'}},
            {label:'NavajoWhite',            value:{id:1, name: 'NavajoWhite',           code: '#FFDEAD'}},
            {label:'Navy',                   value:{id:1, name: 'Navy',                  code: '#000080'}},
            {label:'OldLace',                value:{id:1, name: 'OldLace',               code: '#FDF5E6'}},
            {label:'Olive',                  value:{id:1, name: 'Olive',                 code: '#808000'}},
            {label:'OliveDrab',              value:{id:1, name: 'OliveDrab',             code: '#6B8E23'}},
            {label:'Orange',                 value:{id:1, name: 'Orange',                code: '#FFA500'}},
            {label:'OrangeRed',              value:{id:1, name: 'OrangeRed',             code: '#FF4500'}},
            {label:'Orchid',                 value:{id:1, name: 'Orchid',                code: '#DA70D6'}},
            {label:'PaleGoldenRod',          value:{id:1, name: 'PaleGoldenRod',         code: '#EEE8AA'}},
            {label:'PaleGreen',              value:{id:1, name: 'PaleGreen',             code: '#98FB98'}},
            {label:'PaleTurquoise',          value:{id:1, name: 'PaleTurquoise',         code: '#AFEEEE'}},
            {label:'PaleVioletRed',          value:{id:1, name: 'PaleVioletRed',         code: '#DB7093'}},
            {label:'PapayaWhip',             value:{id:1, name: 'PapayaWhip',            code: '#FFEFD5'}},
            {label:'PeachPuff',              value:{id:1, name: 'PeachPuff',             code: '#FFDAB9'}},
            {label:'Peru',                   value:{id:1, name: 'Peru',                  code: '#CD853F'}},
            {label:'Pink',                   value:{id:1, name: 'Pink',                  code: '#FFC0CB'}},
            {label:'Plum',                   value:{id:1, name: 'Plum',                  code: '#DDA0DD'}},
            {label:'PowderBlue',             value:{id:1, name: 'PowderBlue',            code: '#B0E0E6'}},
            {label:'Purple',                 value:{id:1, name: 'Purple',                code: '#800080'}},
            {label:'RebeccaPurple',          value:{id:1, name: 'RebeccaPurple',         code: '#663399'}},
            {label:'Red',                    value:{id:1, name: 'Red',                   code: '#FF0000'}},
            {label:'RosyBrown',              value:{id:1, name: 'RosyBrown',             code: '#BC8F8F'}},
            {label:'RoyalBlue',              value:{id:1, name: 'RoyalBlue',             code: '#4169E1'}},
            {label:'SaddleBrown',            value:{id:1, name: 'SaddleBrown',           code: '#8B4513'}},
            {label:'Salmon',                 value:{id:1, name: 'Salmon',                code: '#FA8072'}},
            {label:'SandyBrown',             value:{id:1, name: 'SandyBrown',            code: '#F4A460'}},
            {label:'SeaGreen',               value:{id:1, name: 'SeaGreen',              code: '#2E8B57'}},
            {label:'SeaShell',               value:{id:1, name: 'SeaShell',              code: '#FFF5EE'}},
            {label:'Sienna',                 value:{id:1, name: 'Sienna',                code: '#A0522D'}},
            {label:'Silver',                 value:{id:1, name: 'Silver',                code: '#C0C0C0'}},
            {label:'SkyBlue',                value:{id:1, name: 'SkyBlue',               code: '#87CEEB'}},
            {label:'SlateBlue',              value:{id:1, name: 'SlateBlue',             code: '#6A5ACD'}},
            {label:'SlateGray',              value:{id:1, name: 'SlateGray',             code: '#708090'}},
            {label:'SlateGrey',              value:{id:1, name: 'SlateGrey',             code: '#708090'}},
            {label:'Snow',                   value:{id:1, name: 'Snow',                  code: '#FFFAFA'}},
            {label:'SpringGreen',            value:{id:1, name: 'SpringGreen',           code: '#00FF7F'}},
            {label:'SteelBlue',              value:{id:1, name: 'SteelBlue',             code: '#4682B4'}},
            {label:'Tan',                    value:{id:1, name: 'Tan',                   code: '#D2B48C'}},
            {label:'Teal',                   value:{id:1, name: 'Teal',                  code: '#008080'}},
            {label:'Thistle',                value:{id:1, name: 'Thistle',               code: '#D8BFD8'}},
            {label:'Tomato',                 value:{id:1, name: 'Tomato',                code: '#FF6347'}},
            {label:'Turquoise',              value:{id:1, name: 'Turquoise',             code: '#40E0D0'}},
            {label:'Violet',                 value:{id:1, name: 'Violet',                code: '#EE82EE'}},
            {label:'Wheat',                  value:{id:1, name: 'Wheat',                 code: '#F5DEB3'}},
            {label:'White',                  value:{id:1, name: 'White',                 code: '#FFFFFF'}},
            {label:'WhiteSmoke',             value:{id:1, name: 'WhiteSmoke',            code: '#F5F5F5'}},
            {label:'Yellow',                 value:{id:1, name: 'Yellow',                code: '#FFFF00'}},
            {label:'YellowGreen',            value:{id:1, name: 'YellowGreen',           code: '#9ACD32'}}
        ];
    }

    getColors(): SelectItem[] {
        return this.colors;
    }
}